plugins {
    id 'com.android.application'
}

android {
    namespace 'com.msdk.aihelp.demo'
    compileSdk 34

    defaultConfig {
        applicationId 'com.msdk.aihelp.demo'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '1.0.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation project(':sdk')
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
